### ISSUE TITLE
Design objectives

### ISSUE THREAD

**Issue by pawel-kow** [SIDN/ietf-epp-restful-json#5]
I think this document is lacking on design objectives, which would help a lot to take some decisions.

Some points I would think of:
- is it required to be able to losslessly convert XML EPP to JSON EPP and then back to XML EPP?
- is it required to cover all possible constructs that XML offers, which may in the future used by any EPP extension or RFC, or shall design consider only those features, which are already present in the existing EPP specifications and extensions
- shall "prior art" be considered in the design decisions, such as registration APIs from .fr or .ee or even RDAP?
- shall it be important to have easy possibility of binding objects in the programming languages? This may mean that some characters in the property names are better be avoided, or that the same properties are always of the same data type
- shall it be important to have smaller representations as opposed to more verbose ones? Namespaces is a good example where you can be verbose with prefixing all properties or have smaller overhead leaving it aside or finding another solution
- shall features be added beyond EPP, like HATEOAS which would be a new feature for REPP (actually for both representations XML or JSON) resulting from availability of resource addressability through URIs.
- are some new client types (???) in the consideration here?

**Comment by mwullink** [comment]
thx!
i'm going to create an issue for each objective
